<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_User Management Job Organization Qualifi_9378c0</name>
   <tag></tag>
   <elementGuidId>30770bc8-a54a-4111-be28-5e6d0efc5465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/header/div[2]/nav/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.oxd-topbar-body-nav > ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>697c933a-925b-4170-968b-9500413a1271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Management Job Organization Qualifications NationalitiesCorporate BrandingConfiguration </value>
      <webElementGuid>a7b69fe2-de37-439b-9eba-3803fd5cac49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-navigation&quot;]/header[@class=&quot;oxd-topbar&quot;]/div[@class=&quot;oxd-topbar-body&quot;]/nav[@class=&quot;oxd-topbar-body-nav&quot;]/ul[1]</value>
      <webElementGuid>14c43ae0-94c9-4620-b87a-674a94e41d4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/header/div[2]/nav/ul</value>
      <webElementGuid>38ffb944-6d9d-433c-ab6d-335897afcb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul</value>
      <webElementGuid>55626933-3a14-44b5-8de6-e338fc916088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'User Management Job Organization Qualifications NationalitiesCorporate BrandingConfiguration ' or . = 'User Management Job Organization Qualifications NationalitiesCorporate BrandingConfiguration ')]</value>
      <webElementGuid>7b3f9695-9432-4eca-962f-27e81da6a93c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
